spring:
  datasource:
    url: jdbc:h2:mem:dcl2025
    username: dcl2025
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

# Definindo o perfil ativo como 'dev'
spring:
  profiles:
    active: dev
