spring:
  profiles:
    active: prod  # Define o perfil padrão como produção

  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.service.jta.platform.internal.NoJtaPlatform

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.hibernate: DEBUG
